### ISSUE TITLE
Can't login always get "Are you sure you're not a robot?"

### ISSUE THREAD

**Issue by crsleeth** [talonius/hb-downloader#10]
I've tried putting my session cookie in cookes.txt in multiple different formats. I've also tried both enabling and disabling authy. Every time I try to run the script on Ubuntu 16.04, 17.10, and Windows 10 I get this error:
```
Traceback (most recent call last):
  File "./hb-downloader.py", line 41, in <module>
    hapi.login(ConfigData.username, ConfigData.password, ConfigData.authy_token)
  File "/home/hb/hb-downloader-old/humble_api/humble_api.py", line 133, in login
    error_msg, request=request, response=response, authy_required=authy_required)
humble_api.exceptions.humble_captcha_exception.HumbleCaptchaException: Are you sure you're not a robot? Please try again.
```

My cookies.txt looks like this:
```
#LWP-Cookies-2.0
Set-Cookie3: _simpleauth_sess=""<edited out string>""; path="/"; domain="www.humblebundle.com"; path_spec; secure; expires="1578381372.963161"; HttpOnly=None; version=0
```
I've done the /login to /processlogin fix and tried the python3 MayeulC fork but I get the same issue.

**Comment by felisucoibi** [comment]
You need first to login with your browser, get the cookie and use it in the fork https://github.com/MayeulC/hb-downloader/

**Comment by talonius** [comment]
I've merged Mayeul's fork into the base, but his instructions are accurate.  The CAPTCHA is something that the application cannot manipulate.
