### ISSUE TITLE
Please mention where the configuration file is saved, and also allow per-user configuration files

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [talonius/hb-downloader#15]
I was able to find the configuration file location by reading the source and PKGBUILD on the AUR but it'd help if this was mentioned in the README, and also if it looked for a configuration file on a per-user basis, in the appropriate configuration file directories, say `~/.config/hb-downloader`.

And yes, I'm aware it looks for a configuration file in the pwd, but it's kind of awkward to first have to navigate to the correct directory before calling the executable. 

I may work on a pull request that implements these things at some point but I won't be able to for a while

**Comment by talonius** [comment]
I added the ability to use a ~/.config/hb-downloader-settings.yaml file, and merged in a change that allowed the usage of a /etc/hb-downloader-settings.yaml file.  The priority is user config, system /etc., and local directory.

When the script starts up it also specifies 1) where it's running from and 2) where it's looking for configuration files.

```
Humble Bundle Downloader v0.6.0
This program is not affiliated nor endorsed by Humble Bundle, Inc.
For any suggestion or bug report, please create an issue at:
https://github.com/talonius/hb-downloader/issues

This script is running from and logging to /home/brian/hbd2

Loading configuration from /home/brian/.config/hb-downloader-settings.yaml
Configuration successfully loaded from /home/brian/.config/hb-downloader-settings.yaml

```

**Comment by MadeOfMagicAndWires** [comment]
I don't remember making this issue but cheers!
